[package]
name = "wc_language_tools_extension"
version = "0.0.1"
edition = "2021"
license = "MIT"
publish = false

authors = ["WC Toolkit <opensource@wc-toolkit.dev>"]

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
zed_extension_api = "0.7.0"
