id = "wc-language-server"
name = "Web Components Language Server"
description = "Web Component autocomplete, documentation, and diagnostics powered by the wc-language-server."
version = "0.0.1"
schema_version = 1
authors = ["WC Toolkit <burton@breakstuff.io>"]
repository = "https://github.com/wc-toolkit/wc-language-server"

[language_servers.wc-language-server]
name = "WC Language Server"
languages = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "JSX",
  "TSX",
  "Vue",
  "Astro",
  "MDX"
]

[language_servers.wc-language-server.language_ids]
"HTML" = "html"
"CSS" = "css"
"JavaScript" = "javascript"
"TypeScript" = "typescript"
"JSX" = "javascriptreact"
"TSX" = "typescriptreact"
"Vue" = "vue"
"Astro" = "astro"
"MDX" = "mdx"
